import Head from 'next/head'
import { useState } from 'react'
import * as S from '../styles/index'

export default function Home() {
  const [darkModeIsActive, setDarkModeIsActive] = useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Toggle isActive={darkModeIsActive} onClick={() => setDarkModeIsActive(!darkModeIsActive)} />
      <S.Container>
        <S.DarkMode isActive={darkModeIsActive} />
      </S.Container>
        <S.Title isActive={darkModeIsActive}>Toggle dark mode animation</S.Title>
    </>
  )
}
